---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: macosx-10.10
    driver:
      gui: true

suites:
  - name: default
    run_list:
      - "recipe[homebrew]"
      - "recipe[commandp]"
      - "recipe[commandp::ruby]"
      - "recipe[dmg]"
      - "recipe[commandp::vpn]"
    attributes: